#ifndef __GUI_COMMON_H__
#define __GUI_COMMON_H__

#define GuiDbgPrintf  printf
#define GuiLock()
#define GuiUnlock()
//==========================================================================================
//external resources path
#define EXTERNAL_RESOURCES_ROOT                 "./res/"
//#define EXTERNAL_RESOURCES_ROOT                 "/mnt/sdcard/"

//font
#define FONT_UPF_FILE_PATH_160_50               EXTERNAL_RESOURCES_ROOT "unifont_160_50.upf"
#define FONT_UPF_FILE_PATH_SZSimHei_32_32       EXTERNAL_RESOURCES_ROOT "SZSimHei-UTF-8-32-32.upf"

//icon
#define ICON_FILE_PATH_ICON_SUCC_NORMAL        EXTERNAL_RESOURCES_ROOT "icon_succ.png"
#define ICON_FILE_PATH_ICON_FAIL_NORMAL        EXTERNAL_RESOURCES_ROOT "icon_fail.png"
#define ICON_FILE_PATH_ICON_WARNING_NORMAL     EXTERNAL_RESOURCES_ROOT "icon_warning.png"
#define ICON_FILE_PATH_ICON_WARNING_SMALL      EXTERNAL_RESOURCES_ROOT "icon_warning_small.png"

//image
#define IMAGE_FILE_PATH_MAIN_BG                 EXTERNAL_RESOURCES_ROOT "main_bg.png"
#define IMAGE_FILE_PATH_MAIN_TIP_BG             EXTERNAL_RESOURCES_ROOT "c_tipBg.png"
#define IMAGE_FILE_PATH_MAIN_BATT_0             EXTERNAL_RESOURCES_ROOT "main_batt_0.png"
#define IMAGE_FILE_PATH_MAIN_BATT_1             EXTERNAL_RESOURCES_ROOT "main_batt_1.png"
#define IMAGE_FILE_PATH_MAIN_BATT_2             EXTERNAL_RESOURCES_ROOT "main_batt_2.png"
#define IMAGE_FILE_PATH_MAIN_BATT_3             EXTERNAL_RESOURCES_ROOT "main_batt_3.png"
#define IMAGE_FILE_PATH_MAIN_WIFI_0             EXTERNAL_RESOURCES_ROOT "main_wifi_0.png"
#define IMAGE_FILE_PATH_MAIN_WIFI_1             EXTERNAL_RESOURCES_ROOT "main_wifi_1.png"
#define IMAGE_FILE_PATH_MAIN_WIFI_2             EXTERNAL_RESOURCES_ROOT "main_wifi_2.png"
#define IMAGE_FILE_PATH_MAIN_WIFI_3             EXTERNAL_RESOURCES_ROOT "main_wifi_3.png"
#define IMAGE_FILE_PATH_MAIN_MENU_BUTTON        EXTERNAL_RESOURCES_ROOT "main_btnMenu.png"
#define IMAGE_FILE_PATH_MAIN_NUM_BUTTON         EXTERNAL_RESOURCES_ROOT "main_btnNum.png"

#define IMAGE_FILE_PATH_NUM_KEYPAD_BG           EXTERNAL_RESOURCES_ROOT "main_bg.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_TIP_BG       EXTERNAL_RESOURCES_ROOT "c_tipBg.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_NUM_0        EXTERNAL_RESOURCES_ROOT "numkeypad_0.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_NUM_1        EXTERNAL_RESOURCES_ROOT "numkeypad_1.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_NUM_2        EXTERNAL_RESOURCES_ROOT "numkeypad_2.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_NUM_3        EXTERNAL_RESOURCES_ROOT "numkeypad_3.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_NUM_4        EXTERNAL_RESOURCES_ROOT "numkeypad_4.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_NUM_5        EXTERNAL_RESOURCES_ROOT "numkeypad_5.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_NUM_6        EXTERNAL_RESOURCES_ROOT "numkeypad_6.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_NUM_7        EXTERNAL_RESOURCES_ROOT "numkeypad_7.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_NUM_8        EXTERNAL_RESOURCES_ROOT "numkeypad_8.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_NUM_9        EXTERNAL_RESOURCES_ROOT "numkeypad_9.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_BACK         EXTERNAL_RESOURCES_ROOT "numkeypad_btnBack.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_OK           EXTERNAL_RESOURCES_ROOT "numkeypad_btnOk.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_PASSWORD     EXTERNAL_RESOURCES_ROOT "numkeypad_passwordBg.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_BATT_0       EXTERNAL_RESOURCES_ROOT "main_batt_0.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_BATT_1       EXTERNAL_RESOURCES_ROOT "main_batt_1.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_BATT_2       EXTERNAL_RESOURCES_ROOT "main_batt_2.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_BATT_3       EXTERNAL_RESOURCES_ROOT "main_batt_3.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_WIFI_0       EXTERNAL_RESOURCES_ROOT "main_wifi_0.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_WIFI_1       EXTERNAL_RESOURCES_ROOT "main_wifi_1.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_WIFI_2       EXTERNAL_RESOURCES_ROOT "main_wifi_2.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_WIFI_3       EXTERNAL_RESOURCES_ROOT "main_wifi_3.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_MENU_BUTTON  EXTERNAL_RESOURCES_ROOT "main_btnMenu.png"
#define IMAGE_FILE_PATH_NUM_KEYPAD_RETURN       EXTERNAL_RESOURCES_ROOT "c_btnReturn.png"

//#define IMAGE_FILE_PATH_SHOW_VERIFY_RESULT_MSG_BG_SUCC      EXTERNAL_RESOURCES_ROOT "showverifyresultmsg_bg_succ.png"
//#define IMAGE_FILE_PATH_SHOW_VERIFY_RESULT_MSG_BG_FAIL      EXTERNAL_RESOURCES_ROOT "showverifyresultmsg_bg_fail.png"
//#define IMAGE_FILE_PATH_SHOW_VERIFY_RESULT_MSG_BTN_OK_0     EXTERNAL_RESOURCES_ROOT "showverifyresultmsg_btnOk.png"
//#define IMAGE_FILE_PATH_SHOW_VERIFY_RESULT_MSG_BTN_OK_1     EXTERNAL_RESOURCES_ROOT "showverifyresultmsg_btnOk_1.png"
//#define IMAGE_FILE_PATH_SHOW_VERIFY_RESULT_MSG_BTN_OK_2     EXTERNAL_RESOURCES_ROOT "showverifyresultmsg_btnOk_2.png"
//#define IMAGE_FILE_PATH_SHOW_VERIFY_RESULT_MSG_BTN_OK_3     EXTERNAL_RESOURCES_ROOT "showverifyresultmsg_btnOk_3.png"
//#define IMAGE_FILE_PATH_SHOW_MESSSAGE_BTN_OK                EXTERNAL_RESOURCES_ROOT "showverifyresultmsg_btnOk.png"

#define IMAGE_FILE_PATH_SHOW_MESSSAGE_BOX_BG                EXTERNAL_RESOURCES_ROOT "showmessagebox_bg.png"
#define IMAGE_FILE_PATH_SHOW_MESSSAGE_BOX_QUERY_BG          EXTERNAL_RESOURCES_ROOT "showmessagebox_bg.png"



#define IMAGE_FILE_PATH_VERIFY_FACE_TIP_BG          EXTERNAL_RESOURCES_ROOT "c_tipBg.png"
#define IMAGE_FILE_PATH_VERIFY_FACE_BG              EXTERNAL_RESOURCES_ROOT "verifyFace_bg.png"
#define IMAGE_FILE_PATH_VERIFY_FACE_BT_BG           EXTERNAL_RESOURCES_ROOT "verifyFace_btBg.png"
#define IMAGE_FILE_PATH_VERIFY_FACE_RETURN_BTN      EXTERNAL_RESOURCES_ROOT "c_btnReturn.png"
#define IMAGE_FILE_PATH_VERIFY_FACE_NUMKEY_BTN      EXTERNAL_RESOURCES_ROOT "verifyFace_numkey.png"

#define IMAGE_FILE_PATH_MENU_RETURN_BTN             EXTERNAL_RESOURCES_ROOT "c_btnReturn.png"
#define IMAGE_FILE_PATH_MENU_ADDUSER_BTN            EXTERNAL_RESOURCES_ROOT "menu_addUser.png"
#define IMAGE_FILE_PATH_MENU_USERMANAGE_BTN         EXTERNAL_RESOURCES_ROOT "menu_userManage.png"
#define IMAGE_FILE_PATH_MENU_RECORDMANAGE_BTN       EXTERNAL_RESOURCES_ROOT "menu_recordManage.png"
#define IMAGE_FILE_PATH_MENU_NETSET_BTN             EXTERNAL_RESOURCES_ROOT "menu_netSet.png"
#define IMAGE_FILE_PATH_MENU_SYSTEMSET_BTN          EXTERNAL_RESOURCES_ROOT "menu_systemSet.png"
#define IMAGE_FILE_PATH_MENU_SYSTEMINFO_BTN         EXTERNAL_RESOURCES_ROOT "menu_systemInfo.png"


#define IMAGE_FILE_PATH_EDIT_USER_RETURN_BTN        EXTERNAL_RESOURCES_ROOT "c_btnReturn.png"
#define IMAGE_FILE_PATH_EDIT_USER_ENTER_BTN         EXTERNAL_RESOURCES_ROOT "c_btnEnter.png"

#define IMAGE_FILE_PATH_RECORD_FACE_TIP_BG          EXTERNAL_RESOURCES_ROOT "c_tipBg.png"
#define IMAGE_FILE_PATH_RECORD_FACE_BG              EXTERNAL_RESOURCES_ROOT "verifyFace_bg.png"
#define IMAGE_FILE_PATH_RECORD_FACE_BT_BG           EXTERNAL_RESOURCES_ROOT "verifyFace_btBg.png"
#define IMAGE_FILE_PATH_RECORD_FACE_RETURN_BTN      EXTERNAL_RESOURCES_ROOT "c_btnReturn.png"

#define IMAGE_FILE_PATH_RECORD_PASSWORD_TIP_BG       EXTERNAL_RESOURCES_ROOT "c_tipBg.png"
#define IMAGE_FILE_PATH_RECORD_PASSWORD_BG           EXTERNAL_RESOURCES_ROOT "record_password_bg.png"
#define IMAGE_FILE_PATH_RECORD_PASSWORD_SLEDIT_BG    EXTERNAL_RESOURCES_ROOT "record_password_sledit_bg.png"
#define IMAGE_FILE_PATH_RECORD_PASSWORD_RETURN_BTN   EXTERNAL_RESOURCES_ROOT "c_btnReturn.png"
#define IMAGE_FILE_PATH_RECORD_PASSWORD_ENTER_BTN    EXTERNAL_RESOURCES_ROOT "record_password_enter.png"


#define IMAGE_FILE_PATH_RECORD_RFID_RETURN_BTN       EXTERNAL_RESOURCES_ROOT "c_btnReturn.png"
#define IMAGE_FILE_PATH_RECORD_RFID_FG               EXTERNAL_RESOURCES_ROOT "recode_rfid_fg.png"

#define IMAGE_FILE_PATH_SOFT_KEYPAD_BG              EXTERNAL_RESOURCES_ROOT "softkeypad_bg.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_BACK            EXTERNAL_RESOURCES_ROOT "softkeypad_back.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_EN_LOWER        EXTERNAL_RESOURCES_ROOT "softkeypad_en_lower.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_EN_UPPER        EXTERNAL_RESOURCES_ROOT "softkeypad_en_upper.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_ENTER           EXTERNAL_RESOURCES_ROOT "softkeypad_enter.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_MODE_EN         EXTERNAL_RESOURCES_ROOT "softkeypad_mode_en.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_MODE_NUM        EXTERNAL_RESOURCES_ROOT "softkeypad_mode_num.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_MODE_PINYIN     EXTERNAL_RESOURCES_ROOT "softkeypad_mode_pinyin.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_0           EXTERNAL_RESOURCES_ROOT "softkeypad_num_0.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_1           EXTERNAL_RESOURCES_ROOT "softkeypad_num_1.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_2           EXTERNAL_RESOURCES_ROOT "softkeypad_num_2.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_3           EXTERNAL_RESOURCES_ROOT "softkeypad_num_3.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_4           EXTERNAL_RESOURCES_ROOT "softkeypad_num_4.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_5           EXTERNAL_RESOURCES_ROOT "softkeypad_num_5.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_6           EXTERNAL_RESOURCES_ROOT "softkeypad_num_6.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_7           EXTERNAL_RESOURCES_ROOT "softkeypad_num_7.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_8           EXTERNAL_RESOURCES_ROOT "softkeypad_num_8.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_9           EXTERNAL_RESOURCES_ROOT "softkeypad_num_9.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_EN_CAPS_LOWER   EXTERNAL_RESOURCES_ROOT "softkeypad_en_lower.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_0_EN        EXTERNAL_RESOURCES_ROOT "softkeypad_en_upper.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_1_EN        EXTERNAL_RESOURCES_ROOT "softkeypad_num_1_invalid.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_2_EN        EXTERNAL_RESOURCES_ROOT "softkeypad_num_2_upper.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_3_EN        EXTERNAL_RESOURCES_ROOT "softkeypad_num_3_upper.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_4_EN        EXTERNAL_RESOURCES_ROOT "softkeypad_num_4_upper.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_5_EN        EXTERNAL_RESOURCES_ROOT "softkeypad_num_5_upper.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_6_EN        EXTERNAL_RESOURCES_ROOT "softkeypad_num_6_upper.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_7_EN        EXTERNAL_RESOURCES_ROOT "softkeypad_num_7_upper.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_8_EN        EXTERNAL_RESOURCES_ROOT "softkeypad_num_8_upper.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_9_EN        EXTERNAL_RESOURCES_ROOT "softkeypad_num_9_upper.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_0_PINYIN    EXTERNAL_RESOURCES_ROOT "softkeypad_num_0_invalid.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_1_PINYIN    EXTERNAL_RESOURCES_ROOT "softkeypad_num_1_invalid.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_2_PINYIN    EXTERNAL_RESOURCES_ROOT "softkeypad_num_2_lower.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_3_PINYIN    EXTERNAL_RESOURCES_ROOT "softkeypad_num_3_lower.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_4_PINYIN    EXTERNAL_RESOURCES_ROOT "softkeypad_num_4_lower.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_5_PINYIN    EXTERNAL_RESOURCES_ROOT "softkeypad_num_5_lower.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_6_PINYIN    EXTERNAL_RESOURCES_ROOT "softkeypad_num_6_lower.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_7_PINYIN    EXTERNAL_RESOURCES_ROOT "softkeypad_num_7_lower.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_8_PINYIN    EXTERNAL_RESOURCES_ROOT "softkeypad_num_8_lower.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_NUM_9_PINYIN    EXTERNAL_RESOURCES_ROOT "softkeypad_num_9_lower.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_SPACE           EXTERNAL_RESOURCES_ROOT "softkeypad_space.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_SYMBOL          EXTERNAL_RESOURCES_ROOT "softkeypad_symbol.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_PAGE_PREV       EXTERNAL_RESOURCES_ROOT "c_btnReturn.png"
#define IMAGE_FILE_PATH_SOFT_KEYPAD_PAGE_NEXT       EXTERNAL_RESOURCES_ROOT "c_btnEnter.png"

#define IMAGE_FILE_PATH_USER_MANAGE_RETURN_BTN      EXTERNAL_RESOURCES_ROOT "c_btnReturn.png"
#define IMAGE_FILE_PATH_USER_MANAGE_DEL_ALL_BTN     EXTERNAL_RESOURCES_ROOT "main_btnMenu.png"

#define IMAGE_FILE_PATH_UNLOCK_RECORD_MANAGE_RETURN_BTN      EXTERNAL_RESOURCES_ROOT "c_btnReturn.png"
#define IMAGE_FILE_PATH_UNLOCK_RECORD_MANAGE_DEL_ALL_BTN     EXTERNAL_RESOURCES_ROOT "main_btnMenu.png"

//==========================================================================================

enum eIDC
{
    IDC_MAIN_DIALOGBOX = 101,
    IDC_MAIN_BG_IMAGE,
    IDC_MAIN_TIP_BG_IMAGE,
    IDC_MAIN_WELLCOM_STC,
    IDC_MAIN_BATTERY_IMAGE,
    IDC_MAIN_WIFI_IMAGE,
    IDC_MAIN_MENU_BTN,
    IDC_MAIN_NUM_BTN,
    IDC_MAIN_TIMER,

    IDC_NUM_KEYPAD_DIALOGBOX,
    IDC_NUM_KEYPAD_BG_IMAGE,
    IDC_NUM_KEYPAD_TIP_BG_IMAGE,
    IDC_NUM_KEYPAD_NUM_0_BTN,
    IDC_NUM_KEYPAD_NUM_1_BTN,
    IDC_NUM_KEYPAD_NUM_2_BTN,
    IDC_NUM_KEYPAD_NUM_3_BTN,
    IDC_NUM_KEYPAD_NUM_4_BTN,
    IDC_NUM_KEYPAD_NUM_5_BTN,
    IDC_NUM_KEYPAD_NUM_6_BTN,
    IDC_NUM_KEYPAD_NUM_7_BTN,
    IDC_NUM_KEYPAD_NUM_8_BTN,
    IDC_NUM_KEYPAD_NUM_9_BTN,
    IDC_NUM_KEYPAD_RETURN_BTN,
    IDC_NUM_KEYPAD_BACK_BTN,
    IDC_NUM_KEYPAD_OK_BTN,
    IDC_NUM_KEYPAD_PASSWORD_STC,
    IDC_NUM_KEYPAD_PASSWORD_IMAGE,
    IDC_NUM_KEYPAD_BATTERY_IMAGE,
    IDC_NUM_KEYPAD_WIFI_IMAGE,
    IDC_NUM_KEYPAD_MENU_BTN,
    IDC_NUM_KEYPAD_TIMER,

    IDC_SOFT_KEYPAD_DIALOGBOX,
    IDC_SOFT_KEYPAD_BG_IMAGE,
    IDC_SOFT_KEYPAD_MODE_BTN,
    IDC_SOFT_KEYPAD_NUM_0_BTN,
    IDC_SOFT_KEYPAD_NUM_1_BTN,
    IDC_SOFT_KEYPAD_NUM_2_BTN,
    IDC_SOFT_KEYPAD_NUM_3_BTN,
    IDC_SOFT_KEYPAD_NUM_4_BTN,
    IDC_SOFT_KEYPAD_NUM_5_BTN,
    IDC_SOFT_KEYPAD_NUM_6_BTN,
    IDC_SOFT_KEYPAD_NUM_7_BTN,
    IDC_SOFT_KEYPAD_NUM_8_BTN,
    IDC_SOFT_KEYPAD_NUM_9_BTN,
    IDC_SOFT_KEYPAD_SPACE_BTN,
    IDC_SOFT_KEYPAD_BACK_BTN,
    IDC_SOFT_KEYPAD_SYMBOL_BTN,
    IDC_SOFT_KEYPAD_ENTER_BTN,
    IDC_SOFT_KEYPAD_PAGE_PREV_BTN,
    IDC_SOFT_KEYPAD_PAGE_NEXT_BTN,
    IDC_SOFT_KEYPAD_SELECT_0_BTN,
    IDC_SOFT_KEYPAD_SELECT_1_BTN,
    IDC_SOFT_KEYPAD_SELECT_2_BTN,
    IDC_SOFT_KEYPAD_SELECT_3_BTN,
    IDC_SOFT_KEYPAD_SELECT_4_BTN,
    IDC_SOFT_KEYPAD_SELECT_5_BTN,

    IDC_NUM_SHOW_VERIFY_MSG_DIALOGBOX,
    IDC_NUM_SHOW_VERIFY_MSG_BG_IMAGE,
    IDC_NUM_SHOW_VERIFY_BTN_OK,
    IDC_NUM_SHOW_VERIFY_BTN_OK_STC,

    IDC_SHOW_MESSAGE_BOX_DIALOGBOX,
    IDC_SHOW_MESSAGE_BOX_BG_IMAGE,
    IDC_SHOW_MESSAGE_BOX_ICON_IMAGE,
    IDC_SHOW_MESSAGE_BOX_STR_STC,
    IDC_SHOW_MESSAGE_BOX_OK_BTN,

    IDC_SHOW_MESSAGE_BOX_QUERY_DIALOGBOX,
    IDC_SHOW_MESSAGE_BOX_QUERY_BG_IMAGE,
    IDC_SHOW_MESSAGE_BOX_QUERY_ICON_IMAGE,
    IDC_SHOW_MESSAGE_BOX_QUERY_STR_STC,
    IDC_SHOW_MESSAGE_BOX_QUERY_YES_BTN,
    IDC_SHOW_MESSAGE_BOX_QUERY_NO_BTN,

    IDC_VERIFY_FACE_DIALOGBOX,
    IDC_VERIFY_FACE_TIP_BG_IMAGE,
    IDC_VERIFY_FACE_BG_IMAGE,
    IDC_VERIFY_FACE_BT_BG_IMAGE,
    IDC_VERIFY_FACE_RETURN_BTN,
    IDC_VERIFY_FACE_NUMKEY_BTN,
    IDC_VERIFY_FACE_STATE_BT_STATIC,

    IDC_MENU_DIALOGBOX,
    IDC_MENU_RETURN_BTN,
    IDC_MENU_TIP_STC,
    IDC_MENU_ADDUSER_BTN,
    IDC_MENU_USERMANAGE_BTN,
    IDC_MENU_RECORDMANAGE_BTN,
    IDC_MENU_NETSET_BTN,
    IDC_MENU_SYSTEMSET_BTN,
    IDC_MENU_SYSTEMINFO_BTN,
    IDC_MENU_ADDUSER_STC,
    IDC_MENU_USERMANAGE_STC,
    IDC_MENU_RECORDMANAGE_STC,
    IDC_MENU_NETSET_STC,
    IDC_MENU_SYSTEMSET_STC,
    IDC_MENU_SYSTEMINFO_STC,

    IDC_EDIT_USER_DIALOGBOX,
    IDC_EDIT_USER_RETURN_BTN,
    IDC_EDIT_USER_TIP_STC,
    IDC_EDIT_USER_USERID_RECT,
    IDC_EDIT_USER_USERID_STC_LEFT,
    IDC_EDIT_USER_USERID_STC_RIGHT,
    IDC_EDIT_USER_USERNAME_RECT,
    IDC_EDIT_USER_USERNAME_STC_LEFT,
    IDC_EDIT_USER_USERNAME_STC_RIGHT,
    IDC_EDIT_USER_RECORDFACE_RECT,
    IDC_EDIT_USER_RECORDFACE_STC_LEFT,
    IDC_EDIT_USER_RECORDFACE_STC_RIGHT,
    IDC_EDIT_USER_RECORDFACE_BTN,
    IDC_EDIT_USER_RECORDPASSWORD_RECT,
    IDC_EDIT_USER_RECORDPASSWORD_STC_LEFT,
    IDC_EDIT_USER_RECORDPASSWORD_STC_RIGHT,
    IDC_EDIT_USER_RECORDPASSWORD_BTN,
    IDC_EDIT_USER_RECORDRFID_RECT,
    IDC_EDIT_USER_RECORDRFID_STC_LEFT,
    IDC_EDIT_USER_RECORDRFID_STC_RIGHT,
    IDC_EDIT_USER_RECORDRFID_BTN,
    IDC_EDIT_USER_USERAUTH_RECT,
    IDC_EDIT_USER_USERAUTH_STC_LEFT,
    IDC_EDIT_USER_USERAUTH_STC_RIGHT,
    IDC_EDIT_USER_USERAUTH_BTN,
    IDC_EDIT_USER_USERAUTH_ADMIN_BTN,
    IDC_EDIT_USER_USERAUTH_CUSTOMER_BTN,
    IDC_EDIT_USER_SAVE_BTN,

    IDC_RECORD_FACE_DIALOGBOX,
    IDC_RECORD_FACE_TIP_BG_IMAGE,
    IDC_RECORD_FACE_TIP_STC,
    IDC_RECORD_FACE_BG_IMAGE,
    IDC_RECORD_FACE_BT_BG_IMAGE,
    IDC_RECORD_FACE_BT_BG_RECT,
    IDC_RECORD_FACE_RETURN_BTN,
    IDC_RECORD_FACE_STATE_BT_STC,
    IDC_RECORD_FACE_START_BTN,

    IDC_RECORD_PASSWORD_DIALOGBOX,
    IDC_RECORD_PASSWORD_TIP_BG_IMAGE,
    IDC_RECORD_PASSWORD_BG_IMAGE,
    IDC_RECORD_PASSWORD_SLEDIT_BG_IMAGE,
    IDC_RECORD_PASSWORD_STATE_IMAGE,
    IDC_RECORD_PASSWORD_RETURN_BTN,
    IDC_RECORD_PASSWORD_TIP_STC,
    IDC_RECORD_PASSWORD_SLEDIT_HEAD_STC,
    IDC_RECORD_PASSWORD_PASSWORD_EDIT_1,
    IDC_RECORD_PASSWORD_PASSWORD_EDIT_2,
    IDC_RECORD_PASSWORD_STATE_STC,
    IDC_RECORD_PASSWORD_ENTER_BTN,

    IDC_RECORD_RFID_DIALOGBOX,
    IDC_RECORD_RFID_TIP_STC,
    IDC_RECORD_RFID_FG_IMAGE,
    IDC_RECORD_RFID_RETURN_BTN,
    IDC_RECORD_RFID_STATE_STC,

    IDC_USER_MANAGE_DIALOGBOX,
    IDC_USER_MANAGE_RETURN_BTN,
    IDC_USER_MANAGE_TIP_STC,
    IDC_USER_MANAGE_LISTVIEW,
    IDC_USER_MANAGE_DELETE_ALL_BTN,
    IDC_USER_MANAGE_HEADER_RECT,
    IDC_USER_MANAGE_BOTTOM_RECT,
    IDC_USER_MANAGE_HEADER_NAME_STC,
    IDC_USER_MANAGE_HEADER_ID_STC,
    IDC_USER_MANAGE_HEADER_AUTH_STC,
    IDC_USER_MANAGE_PAGE_STATUS_STC,
    IDC_USER_MANAGE_PREV_PAGE_BTN,
    IDC_USER_MANAGE_NEXT_PAGE_BTN,

	IDC_UNLOCK_RECORD_MANAGE_DIALOGBOX,
    IDC_UNLOCK_RECORD_MANAGE_RETURN_BTN,
    IDC_UNLOCK_RECORD_MANAGE_TIP_STC,
    IDC_UNLOCK_RECORD_MANAGE_LISTVIEW,
    IDC_UNLOCK_RECORD_MANAGE_DELETE_ALL_BTN,
    IDC_UNLOCK_RECORD_MANAGE_HEADER_RECT,
    IDC_UNLOCK_RECORD_MANAGE_BOTTOM_RECT,
    IDC_UNLOCK_RECORD_MANAGE_HEADER_NAME_STC,
    IDC_UNLOCK_RECORD_MANAGE_HEADER_ID_STC,
    IDC_UNLOCK_RECORD_MANAGE_HEADER_AUTH_STC,
    IDC_UNLOCK_RECORD_MANAGE_PAGE_STATUS_STC,
    IDC_UNLOCK_RECORD_MANAGE_PREV_PAGE_BTN,
    IDC_UNLOCK_RECORD_MANAGE_NEXT_PAGE_BTN,
};

#define MSG_USR_CHILD_RETURN  (MSG_USER +1)

enum eBatteryLevel{

	MAIN_BATT_0 = 0,
	MAIN_BATT_1,
	MAIN_BATT_2,
	MAIN_BATT_3,
	MAIN_BATT_MAX
};

enum eWifiStatus{

	MAIN_WIFI_0 = 0,
	MAIN_WIFI_1,
	MAIN_WIFI_2,
	MAIN_WIFI_3,
	MAIN_WIFI_MAX
};

//==========================================================================================
extern LOGFONT* logfont_unifont_SZSimHei_UTF_8_32_32;

extern LOGFONT * logfont_unifont_160_50;

#define logfont_unifont_default logfont_unifont_SZSimHei_UTF_8_32_32
#define GetCurUserLogfont() logfont_unifont_SZSimHei_UTF_8_32_32

extern void LoadIncoreData();
extern void UnloadIncoreData();


//==========================================================================================
typedef enum
{
    eVERIFY_TYPE_OPEN_DOOR = 0,
    eVERIFY_TYPE_CUSTOMER,
    eVERIFY_TYPE_ADMIN,
}eVERIFY_TYPE;

extern BOOL GuiVerifyPassword(char* str, eVERIFY_TYPE type);
extern BOOL GuiVerifyFace(void * face, eVERIFY_TYPE type);
extern BOOL GuiVerifyRfid(void * rfid, eVERIFY_TYPE type);
//==========================================================================================
#define MAX_USER_INFO_NUM    20U
#define MAX_USER_NAME_LEN    31U
#define MAX_PASSWORD_LEN     20U
typedef enum
{
    eUSER_TYPE_CUSTOMER = 0,
    eUSER_TYPE_ADMIN,
}eUSER_TYPE;

typedef struct
{
    BOOL isValid;
    uint32_t id;
    eUSER_TYPE type;
    char name[MAX_USER_NAME_LEN +1];
    char password[MAX_PASSWORD_LEN +1];
    void * pic;
    void * face;
    void * rfid;
}sUSER_INFO;

typedef struct
{
    BOOL isValid;
    eUSER_TYPE type;
    char name[MAX_USER_NAME_LEN +1];
    char password[MAX_PASSWORD_LEN +1];
    uint32_t faceId;
    void * pic;
    void * face;   //not used
    void * rfid;   //not used
}structUserInfo;

//return 0 means no Admin
extern uint32_t GuiGetAdminCount();

//return 0 means no customer
extern uint32_t GuiGetCustomerCount();

//if the value greater than (MAX_USER_INFO_NUM - 1), means no unused id
extern uint32_t GuiApplyUserInfoId(void);

extern BOOL GuiIsUserInfoValid(uint32_t id);

//return FALSE means no valid info
extern BOOL GuiReadUserInfo(uint32_t id, sUSER_INFO * pUserInfoOut);
//==========================================================================================
#endif  //__GUI_COMMON_H__
//end files

